###
GET http://localhost:8080/
###
POST http://localhost:8080/location
Content-Type: application/json

{
  "lat": 33.982374,
  "long": -118.282664
}
###
POST http://localhost:8080/neighbors-flight
Content-Type: application/json

[
  {
    "lat": 33.9978617,
    "long": -118.3936166,
    "radius": 5
  },
  {
    "lat": 34.0522,
    "long": -118.2437,
    "radius": 3
  },
  {
    "lat": 33.891769,
    "long": -118.297006,
    "radius": 2
  }
]

###
POST http://localhost:8080/neighbors-driving
Content-Type: application/json

{
  "lat": 34.0762187,
  "long": -118.3109634,
  "radius": 20
}



###
POST https://traffic.wearewarp.link/traffic
Content-Type: application/json

{
  "from": [[34.0659747, -118.2386422],[34.0609873, -118.2998843]],
  "to": [[34.0593736, -118.3089617],[34.0530983,-118.2645052]]
}